#!/usr/bin/env python
# A script to convert the tsv generated by capture_image_base64.py to image frames.
# Usage : ./base64_image_decoder.py logfile foldername

import numpy as np
import base64
import sys
import os

if len(sys.argv)<2:
    print "Usage : ./base64_image_decoder.py logfile [foldername]"
    sys.exit(0)

log_file = sys.argv[1]
if len(sys.argv)==3:
    directory=sys.argv[2]
else:
    directory=sys.argv[1].split(".")[0]
os.mkdir(directory)

with open(log_file) as infile:
    lines = infile.readlines()
for line in lines:
    data = line.split("\t")
    data[0]+=".jpg"
    data_jpeg=data[1].decode('base64')
    with open(os.path.join(directory,data[0]),"wb") as outfile:
        outfile.write(data_jpeg)
    


